#!/usr/bin/env bash

echo "clear-ci-nix-cache: Clearing ${GITHUB_REPOSITORY} nix cache..."

gh api --paginate -H "Accept: application/vnd.github+json" \
  "/repos/${GITHUB_REPOSITORY}/actions/caches" \
  | for ID in `jq '.actions_caches[].id'`; \
    do echo "Deleting $ID"; \
       gh api --method DELETE "/repos/${GITHUB_REPOSITORY}/actions/caches/$ID" | echo; done

echo "clear-ci-nix-cache: all done"
